feature/BRI-20
brilliant-hamsters/quiz-game pull request #14
Opened 2023-03-31 19:32 UTC by Swizzy11

### Подготовил ветку для Epic задачи : Profile

2023-04-07 06:16 UTC, AndreyTsvetkov requested changes
один структурный момент, и несколько стилистических

2023-04-07 06:16 UTC, AndreyTsvetkov commented on packages/client/src/api/apiService.ts
>  export const sendApiRequest = async (path: string, options?: IApiOptions) => {
Я бы изменил распределение ответственности между компонентами. `sendApiRequest` сейчас - такой метод с размытой ответственностью, он с одной стороны и знает что-то конкретику апи, с которым работает, например, что на `'/user/profile/avatar'` не нужно слать заголовки, но с другой стороны, не знает при этом, что метод там нужен PUT, это знание разделено между методом и его клиентом и это нехорошо.

Поменяется адрес  user/profile/avatar, в одном месте поменяем, в другом забудем, будет ошибка. Потому что нарушен принцип SRP (https://habr.com/ru/articles/454290/)

Раз есть конкретные типизированные методы типа `updateUserAvatar` (и хорошо, что они есть), которые в реализации вызывают этот, пусть между ними будет четкое разделение ответственности:

- `updateUserAvatar` внутри знает всё о том, как и что передать
- `sendApiRequest` просто передает, как удобная обертка над fetch

Для этого я бы

1. в методе `sendApiRequest` вынес бы `method` из `options` в список параметров напрямую, а `options`? оставил вообще `any`, т.к. перечислять там все текущие и будущие возможные типы параметров многословно, а ценности особой не добавляет, все равно над  `sendApiRequest` будут нормальные типизированные обертки
2. добавил туда же параметр bool `useDefaultHeaders = true` (или `= false`, смотря что чаще нужно)

и тем самым избавился от всей условной логики в методе, кроме выбора JSON.stringify или FormData. 
Он остается простой оберткой на fetch. 
  
3. во всех вызовах, таких как в `updateUserAvatar`, явно указал бы метод и `useDefaultHeaders` и тем самым  сосредоточил в них всю значимую информацию о данном endpoint-е АПИ.

2023-04-07 06:16 UTC, AndreyTsvetkov commented on packages/client/src/api/methods/updateUserData.ts
> +    first_name:string;
не могу принять в одном проекте, а тем более в одном PR два стиля именования свойств: `first_name` и `newPassword`. Выберите с командой один, и следуйте везде. Обычно для TS это `newPassword`

2023-04-07 06:16 UTC, AndreyTsvetkov commented on packages/client/src/components/block/Achievements/Achievements.tsx
> +    achieve_text:string;
и линтер надо бы напустить. двоеточие отбивается пробелом после.

2023-04-07 06:16 UTC, AndreyTsvetkov commented on packages/client/src/store/profile/profileSlice.ts
> +interface IInitState {
нужна отбивка от списка импортов, иначе не читается

2023-04-07 19:56 UTC, Swizzy11 commented on packages/client/src/api/methods/updateUserData.ts
> +    first_name:string;
К сожалению не могу это исправить, тк тело запроса в swagger именно такое, в разных стилях.

2023-04-08 14:39 UTC, AndreyTsvetkov approved these changes

2023-04-08 17:39 UTC, merged