feature/BRI-21
brilliant-hamsters/quiz-game pull request #15
Opened 2023-03-31 19:33 UTC by Swizzy11

### Вёрстка страницы Профиля

2023-04-04 13:46 UTC, EfimOstrovskiy commented on packages/client/src/components/block/Achievements/Achievements.module.scss
> +.achievements__p {
та же ошибка в нейминге) в этом должно быть так: .root .icon .title

2023-04-04 13:49 UTC, EfimOstrovskiy commented
тут апрув авансом будет, так как страница профиля очень нагруженная вышла, все что внури нее  минимум на 2 дополнительных компонента можно декомпозировать, но сделаем это позже в рамках рефакторига

2023-04-05 11:19 UTC, EfimOstrovskiy approved these changes

2023-04-05 11:59 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.module.scss
> +        .message {
Здесь та же проблема со вложенностью стилей

2023-04-05 12:02 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.module.scss
> +    &:hover {
Вот здесь хорошо

2023-04-05 12:08 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.module.scss
> +.buttonEditPass:enabled:hover {
Вот здесь было бы классно со ссылкой на родителя селектора:
```
.buttonEditPass{
    &:enabled{
        ...
        &:hover{
            ...
         }
    }
}
```

2023-04-05 12:22 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.tsx
> +                            <div className={styles.userData}>Имя: <input  className={styles.input} name="first_name"  placeholder={""} disabled/></div>
Вместо div нужен label

2023-04-05 12:24 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.tsx
> +                            <div className={styles.userData}>Фамилия: <input  className={styles.input} name="second_name" placeholder={""} disabled/></div>
Вырубить все поля разом можно обернув их в fieldset.  Тогда задав ему disabled, все поля в него входящие станут неактивны

2023-04-05 12:37 UTC, Leliya requested changes
Почитай про хуки состояния. Очень поможет в этом компоненте
https://ru.reactjs.org/docs/hooks-state.html
и еще про условный рендеринг
https://ru.reactjs.org/docs/conditional-rendering.html

2023-04-06 07:01 UTC, merged