feature/BRI-22
brilliant-hamsters/quiz-game pull request #17
Opened 2023-04-02 07:18 UTC by Swizzy11

### Добавление api на страницу профиля

2023-04-02 07:36 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.tsx
> +        const avatarControl = document.querySelector<HTMLFormElement>(`.${styles.avatarControl}`);
ты можешь получить доступ к элементу как event.target

2023-04-02 07:39 UTC, Leliya commented on packages/client/src/pages/Profile/Profile.tsx
> +        if(avatarControl) {
я добавляла img в FormData таким образом
```
 const fileList: FileList | null = element.files;
 const formData = new FormData();
 formData.append('avatar', fileList[0], "имя файла");
```

2023-04-04 13:59 UTC, EfimOstrovskiy commented on packages/client/src/components/block/Achievements/Achievements.tsx
> +
тут этого компонента быть не должно, задача на верстку у тебя готова, надо убрать

2023-04-04 13:59 UTC, EfimOstrovskiy commented on packages/client/src/pages/Profile/Profile.tsx
> +    const dispatch = useAppDispatch();
тут этого компонента быть не должно, задача на верстку у тебя готова, надо убрать

2023-04-04 13:59 UTC, EfimOstrovskiy commented on packages/client/src/store/profile/profileSlice.ts
> +// для получения данных авторизированного пользака
эти коменты надо убрать

2023-04-04 13:59 UTC, EfimOstrovskiy commented on packages/client/src/store/profile/profileSlice.ts
> +        password: payload.data
эта ручка вроде просто возвращает статус что все ок, для пароля не нужен стор, надо убрать это поле

2023-04-04 13:59 UTC, EfimOstrovskiy commented on packages/client/src/store/profile/profileSlice.ts
> +        avatar: payload.data
с аватаром также, данные об фото будут приходить в объект user, поэтому отдельный стор под аву не требуется, надо убрать это поле

2023-04-05 09:09 UTC, EfimOstrovskiy approved these changes

2023-04-05 11:07 UTC, Leliya commented on packages/client/src/api/methods/updateUserData.ts
> +        body: {...data}
Посредством {...data} ты просто копируешь объект. Копирование поверхностное, поэтому потенциально это может вызвать проблемы для объектов со вложенностью.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_в_литералах_объекта

2023-04-05 11:09 UTC, Leliya commented on packages/client/src/store/profile/profileSlice.ts
> +  user: Record<string, string> | null;
У тебя же уже есть интерфейс для юзера, нужно просто добавить его.

2023-04-05 11:11 UTC, Leliya commented on packages/client/src/store/profile/profileSlice.ts
> +  password: Record<string, string> | null;
avatar и password можно включить в user, но сделать их необязательными и потом например вытаскивать их через Pick

2023-04-05 11:44 UTC, Leliya commented on packages/client/src/store/profile/profileSlice.ts
> +  if(!result.ok) {
Здесь и ниже то, о чем я говорила. Если мы из apiService возвращаем result.json() значит result.ok уже не существует. Поэтому лучше возвращать исходный result.  А уже в createAsyncThunk преобразовывать по необходимости в json

2023-04-05 11:53 UTC, Leliya requested changes
Возможно правки в apiService нужно будет вносить после вливания моей ветки. Нужно посоветоваться с @EfimOstrovskiy

2023-04-05 12:47 UTC, Leliya commented on packages/client/src/store/profile/profileSlice.ts
> +  user: Record<string, string> | null;
Я имела в виду вот так
`user: IUserData  | null;`

2023-04-05 12:48 UTC, Leliya approved these changes

2023-04-06 06:25 UTC, merged