feat (BRI-27) Верстка старта игры
brilliant-hamsters/quiz-game pull request #18
Opened 2023-04-02 15:09 UTC by Wrestler094

### Какую задачу решаем
Реализована верстка старта игры

### Скриншоты/видяшка (если есть)
![Снимок экрана 2023-04-02 180627](https://user-images.githubusercontent.com/23001740/229361598-22d5b425-1508-4dca-b7ca-1d1498c74318.png)

2023-04-05 13:32 UTC, AndreyTsvetkov requested changes

2023-04-05 13:32 UTC, AndreyTsvetkov commented on packages/client/src/layouts/GameLayout/GameLayout.tsx
> +interface IGameLayout {
Насколько я могу судить, никто более в команде, да и вообще в практике на TS не предваряют интерфейсы префиксом I.
Лучше бы это унифицировать.

Менее всего бы название удивляло, если бы заканчивалось на Props: `GameLayoutProps`

2023-04-07 05:29 UTC, AndreyTsvetkov approved these changes

2023-04-07 06:58 UTC, artemii258 approved these changes

2023-04-07 16:48 UTC, merged