feat (BRI-41) Разработка движка игры по документации
brilliant-hamsters/quiz-game pull request #28
Opened 2023-04-10 11:32 UTC by EfimOstrovskiy

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-12 12:03 UTC, Leliya commented on packages/client/src/engine/QuizGame.ts
> +import * as question from './questions.json';
Так мы импортируем объект default и json не подгружается. 
Вот так работает:
import question from './questions.json';

2023-04-12 12:17 UTC, Leliya commented on packages/client/src/engine/QuizGame.ts
> +  config: Record<string, number | string | string[] | boolean>[] | null;
На мой взгляд лучше точно прописать чего мы ждем получить в конфиг. У нас же есть точное понимание какие объекты приходят из json.
Например так:
```
type QuestionType = {
answers:... 
award:... 
correctAnswer:...
question: ...
save: ...
}
config: QuestionType[] | null;

```

2023-04-12 12:21 UTC, Leliya commented on packages/client/src/engine/QuizGame.ts
> +  saveCash: unknown;
Разве здесь и ниже не должно быть просто number?

2023-04-12 12:25 UTC, Leliya commented on packages/client/src/engine/QuizGame.ts
> +    const result: Record<string, number | string | string[] | boolean>[] = [];
Здесь нужно просто расширить тип QuestionType, включив save и award

2023-04-13 12:41 UTC, Tsvetkraft requested changes

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  private configStarted(): QuestionType[] {
название метода не должно формировать утверждение "что-то сделано". оно должно представлять команду "сделай что-то". `startConfig()` если он только начнет процесс конфигурирования или `performConfig()`, если он его полностью выполнит. 

или `buildConfig()`, если его задача - построить объект конфигурации

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  public checkingAnswer(answer: string) {
опять же, `проверяяОтвет` не есть описание команды к выполнению. `проверьОтвет` - да. `checkAnswer`

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  numberQuestion: number;
по-ангглийски наоборот: `questionNumber` или даже лучше `currentQuestionNumber`

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  saveCash: number;
звучит как команда или действие. это сохраненная сумма? `savedCash` тогда

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +    this.config = null;
зачем они не инициализированы сразу при объявлении?

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +        return this.endGame(true);
тут мы возвращаем `number`, а в ветке else - объект `Question`. это очень странное и неожиданное поведение для функции про "проверку ответа". 

Эта функция делает гораздо больше, чем проверку ответа, она весь процесс игры по сути реализует, в масштабе одного шага. 

Так что видимо ее надо  назвать checkAnswerAndMoveNext() и явно указать, что она возвращает, чтобы не делать этот вывод, анализируя вызываемые ей функции: 
`type FinalScore = number;`
`public checkAnswerAndMoveNext = (answer: string) : (FinalScore | Question) => ...
`

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  public startGame() {
кстати, все методы в классе разумно всегда делать стрелочными, чтобы не ловить потом проблемы с привязкой `this`

2023-04-13 12:41 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +        return this.endGame(true);
так понятно, что она делает и что возвращает сразу из ее заголовка

2023-04-15 19:49 UTC, Tsvetkraft requested changes

2023-04-15 19:49 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +    this.config = null;
это всё еще актуально

2023-04-15 19:49 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +          if (iterationCount !== 4) {
теперь корректнее, но всё еще неочевидно, что это такое. 4 это 5-1? это читатель не должен догадываться. 5 должно называться `const maxIterations = 5,` а в if должно быть `(maxIterations - 1)`

тогда и вопроса бы не было, и ошибки изначальной, что важно, тоже не было бы!

2023-04-15 19:49 UTC, Tsvetkraft commented on packages/client/src/engine/QuizGame.ts
> +  public startGame() {
методы не стали стрелочными

2023-04-15 21:31 UTC, Tsvetkraft approved these changes

2023-04-19 20:09 UTC, merged