feature/BRI-29
brilliant-hamsters/quiz-game pull request #4
Opened 2023-03-24 21:00 UTC by Swizzy11

### Вёрстка страницы игры | Основное окно

2023-03-25 10:51 UTC, artemii258 approved these changes
ok

2023-03-31 06:27 UTC, Leliya commented on packages/client/src/pages/game_page/game_page.tsx
> +                        <p className={styles.div__time_left}>Time-left:</p>
Класснеймы некорректны. Использование типа тега в наименовании класса  это bad practice. Можно оставить просто header, question, timer и т.д.

2023-03-31 06:31 UTC, Leliya commented on packages/client/src/pages/game_page/game_page.tsx
> +                    <section className={styles.div__body}>
здесь section лучше заменить на список ul, так как это перечисление однородных элементов

2023-03-31 06:32 UTC, Leliya commented on packages/client/src/components/block/block_answer/block_answer.tsx
> +    return <div className={styles.answer}>
здесь лучше сделать элемент списка: <li>

2023-03-31 06:36 UTC, Leliya commented on packages/client/src/pages/game_page/game_page.tsx
> +                <div className={styles.page__link_bar}>
Это по сути навигация и здесь хорошо подойдет тег nav
Но опять таки желательно сделать внутри список с элементами BtnRoute
https://doka.guide/html/nav/

2023-03-31 06:39 UTC, Leliya commented on packages/client/src/components/block/btn_route/btn_route.tsx
> +    return <button className={styles.btn_route}><img src={props.image_path} className={styles.icon}/><p>{props.name_btn}</p></button>
Если используешь img (Хотя на мой взгляд можно обойтись и div), то необходимо добавить alt

2023-03-31 06:40 UTC, Leliya commented on packages/client/src/components/block/btn_route/btn_route.tsx
> +    return <button className={styles.btn_route}><img src={props.image_path} className={styles.icon}/><p>{props.name_btn}</p></button>
Нет смысла оборачивать текст в p. Можно просто стилизовать button

2023-03-31 11:44 UTC, Leliya commented on packages/client/src/components/block/block_answer/block_answer.tsx
> +type answer = {
Название типа лучше писать с большой буквы, например: AnswerProps

2023-03-31 11:45 UTC, Leliya commented on packages/client/src/components/block/btn_route/btn_route.module.scss
> +    background-color:rgba(0, 0, 0, 0);
Чтобы убрать фон можно прописать просто background:none;

2023-03-31 11:48 UTC, Leliya commented on packages/client/src/components/block/btn_route/btn_route.module.scss
> +    font-size: medium;
Здесь не подгрузился шрифт, потому что ты его не указал

2023-03-31 12:09 UTC, Leliya commented on packages/client/src/components/block/btn_route/btn_route.module.scss
> +    font-size: medium;
Лучше использовать конкретные единицы, так как абсолютные значения зависят от настроек браузера и операционной системы. Результат может очень отличатся на разных устройствах

2023-03-31 12:12 UTC, Leliya requested changes
На мой взгляд лучше не злоупотреблять назначение размеров в зависимости от размера вьюпорта. Можно задать для родительского компонента, а для остальных пользоваться % и px

2023-04-02 16:18 UTC, closed without merging