feature/BRI-60 | Добавил OAuth авторизацию
brilliant-hamsters/quiz-game pull request #42
Opened 2023-05-02 13:20 UTC by Swizzy11

### Добавление OAuth авторизации Yandex

2023-05-13 11:41 UTC, EfimOstrovskiy approved these changes

2023-05-16 11:20 UTC, Tsvetkraft requested changes

2023-05-16 11:20 UTC, Tsvetkraft commented on packages/client/src/api/methods/getServiceID.ts
> +export const getServiceID = async (data: ServiceID) => {
с названиями что-то не то

- функция по имени getServiceID должно возвращать ServiceID, а не принимать его
- тип по имени ServiceID должен содержать идентификатор сервиса

Я думаю, `ServiceID` → `ServiceIdCallArgs`, `getServiceID` → `придумать название, описывающее зачем этот вызов`


И надо типизировать возвращаемое значение.

2023-05-16 11:20 UTC, Tsvetkraft commented on packages/client/src/api/methods/sigInWithYandex.ts
> +export type SigInYandex = {
то же, и еще `Sig` → `Sign`

2023-05-16 11:20 UTC, Tsvetkraft commented on packages/client/src/pages/GameStart/GameStart.tsx
> +        {code: String(new URL(window.location.href).searchParams.get('code')), redirect_uri: 'https://quiz-game-client.vercel.app/start'}
выравнивание не по стандарту, не читается

```
dispatch(sigInYandex({
    code: String(new URL(window.location.href).searchParams.get('code')), 
    redirect_uri: 'https://quiz-game-client.vercel.app/start'
}))
```

2023-05-16 11:20 UTC, Tsvetkraft commented on packages/client/src/pages/Login/Login.tsx
> +  function onOauthSubmt() {
опечатка

2023-05-17 10:45 UTC, Swizzy11 commented on packages/client/src/api/methods/getServiceID.ts
> +export const getServiceID = async (data: ServiceID) => {
Насчёт названия метода немного не понял, название подразумевает то, что метод получает ID сервиса

2023-05-17 14:51 UTC, Tsvetkraft commented on packages/client/src/api/methods/getServiceID.ts
> +export const getServiceID = async (data: ServiceID) => {
метод должен называться так, чтобы было понятно, что он _делает и/или возвращает_. этот метод не _возвращает_ ServiceId, он его _получает_, верно же?

2023-05-17 14:55 UTC, Tsvetkraft approved these changes

2023-05-18 10:08 UTC, merged