feature/BRI-59 Настроить Express для Server Side Rendering
brilliant-hamsters/quiz-game pull request #44
Opened 2023-05-08 14:59 UTC by Leliya

Настроить минимальный функционал SSR

2023-05-10 20:18 UTC, artemii258 requested changes

2023-05-10 20:18 UTC, artemii258 commented on packages/server/index.ts
> +  const ssrClientPath = require.resolve('client/ssr-dist/client.cjs')
лучше поменять пути на другие. С этими путями не работает

 const distPath = path.resolve('../client/dist')
  const srcPath = path.resolve('../client')
  const ssrClientPath = path.resolve('../client/ssr-dist/client.cjs')

2023-05-13 11:38 UTC, EfimOstrovskiy approved these changes

2023-05-14 13:11 UTC, artemii258 approved these changes

2023-05-16 11:44 UTC, Tsvetkraft approved these changes

2023-05-16 16:34 UTC, merged