feature/BRI-72  | Добавил темизацию на стороне клиента
brilliant-hamsters/quiz-game pull request #50
Opened 2023-05-25 16:10 UTC by Swizzy11

### Добавил темизацию на стороне клиента
![image](https://github.com/brilliant-hamsters/quiz-game/assets/122433638/eaebef14-b9af-4afd-9db9-1287169c3e11)

2023-05-25 18:46 UTC, EfimOstrovskiy approved these changes

2023-05-28 09:54 UTC, Tsvetkraft requested changes

2023-05-28 09:54 UTC, Tsvetkraft commented on packages/client/src/components/Toggler/Toggler.tsx
> +export const Toggler:FC<TogglerProps> = ({value, onChange}) => {
пробел после ":"

2023-05-28 09:54 UTC, Tsvetkraft commented on packages/client/src/utils/hoc/ChoiceTheme.tsx
> +export const ChoiceTheme = () => {
не по-английски
либо ChooseTheme, либо ThemeChoice

2023-05-28 09:54 UTC, Tsvetkraft commented on packages/client/src/utils/hoc/ChoiceTheme.tsx
> +                            await updateTheme({theme: 'dark'}).then((response) => {if(response.status === 200) setTheme(themes.dark)})
1) точно ли надо ждать ответа сервера, чтобы переключить тему? кажется, что это можно сделать сразу же, а потом асинхронно на сервер сохранить

2) в текущем коде внутри {} не хватает отбивки пробелами внутри {}

2023-05-28 10:39 UTC, Tsvetkraft approved these changes

2023-05-29 16:09 UTC, merged