feature/BRI-74 Поддержать API форума на клиенте
brilliant-hamsters/quiz-game pull request #52
Opened 2023-05-27 10:22 UTC by Leliya

Реализована логика создания новой темы, подгрузка всех тем в список, подгрузка списка сообщений выбранной темы и отправка новых сообщений

2023-05-27 12:02 UTC, EfimOstrovskiy approved these changes

2023-05-27 17:15 UTC, artemii258 approved these changes

2023-05-28 10:36 UTC, Tsvetkraft requested changes

2023-05-28 10:36 UTC, Tsvetkraft commented on packages/client/src/api/methods/getServiceID.ts
>  export const getServiceID = async (data: ServiceIdCallArgs) => {
непоследовательно именование Id - ID - выберите какой-то и примените по проекту

2023-05-28 10:36 UTC, Tsvetkraft commented on packages/client/src/components/Modal/Modal.tsx
> +function stopClose(evt:MouseEvent<HTMLElement>) {
выравнивание сломано, не читается, плюс пробел после :

2023-05-28 10:36 UTC, Tsvetkraft commented on packages/client/src/components/Modal/Modal.tsx
> +function Modal({ isOpen, onClose, onSubmit, validObj, onChange, dataForm }: ModalProps) {
я бы подумал про название. с таким названием может жить компонент, который например обобщает идею модального окна. но это не он. он показывает конкретное окно, и должен (как и его файл) называться, отражая его конкретную ответственность. что-то про выбор темы.

2023-05-29 07:51 UTC, Tsvetkraft approved these changes

2023-05-29 16:09 UTC, merged