feat (BRI-70) Добавление API форума
brilliant-hamsters/quiz-game pull request #53
Opened 2023-05-28 12:21 UTC by Wrestler094

### Какую задачу решаем
Добавление API форума

### Скриншоты/видяшка (если есть)
![image](https://github.com/brilliant-hamsters/quiz-game/assets/23001740/ac65bba0-1972-4e17-a17b-7b1db650a0c5)
![image](https://github.com/brilliant-hamsters/quiz-game/assets/23001740/73586966-4151-46de-b1a9-8f6c576cdc18)

2023-05-28 12:42 UTC, EfimOstrovskiy approved these changes

2023-05-28 18:14 UTC, Tsvetkraft requested changes

2023-05-28 18:14 UTC, Tsvetkraft commented on packages/server/controllers/messages.ts
> +      res.status(400).send('Ничего не изменилось, или что-то пошло не так. Возможно такого id не существует.')
Возможно,

2023-05-28 18:14 UTC, Tsvetkraft commented on packages/server/controllers/themes.ts
> +    res.status(400).send('Bad request: Не передано обязательное поле theme.')
было бы неплохо привести к консистентности язык сообщений - либо русский, либо английский

2023-05-28 18:14 UTC, Tsvetkraft commented on packages/client/tsconfig.json
> +    "noImplicitAny": false,
зачем мы ставим это в false? это хорошая защитная мера

2023-05-29 07:29 UTC, Wrestler094 commented on packages/client/tsconfig.json
> +    "noImplicitAny": false,
Пришлось включить, потому что фронт не собирался в докере. Надо будет исправить фронт и вернуть обратно.

2023-05-29 07:52 UTC, Tsvetkraft commented on packages/server/controllers/messages.ts
> +      res.status(400).send('Ничего не изменилось, или что-то пошло не так. Возможно такого id не существует.')
тут в русском тексте все еще не хватает запятой, ну и тексты все ещё на разных языках

2023-05-29 07:52 UTC, Tsvetkraft commented on packages/client/tsconfig.json
> +    "noImplicitAny": false,
окей

2023-05-29 08:35 UTC, Wrestler094 commented on packages/server/controllers/messages.ts
> +      res.status(400).send('Ничего не изменилось, или что-то пошло не так. Возможно такого id не существует.')
Да, спасибо, залил коммит, постарался привести к одному виду.

2023-05-29 09:11 UTC, Tsvetkraft approved these changes

2023-05-29 16:06 UTC, merged