Feature/bri 80
brilliant-hamsters/quiz-game pull request #65
Opened 2023-06-17 21:08 UTC by Leliya

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-18 06:48 UTC, EfimOstrovskiy approved these changes

2023-06-19 11:22 UTC, Tsvetkraft requested changes

2023-06-19 11:22 UTC, Tsvetkraft commented on packages/server/index.ts
> +const allowLIst: string[] = [
опечатка в слове List

2023-06-19 11:27 UTC, Tsvetkraft approved these changes

2023-06-19 12:45 UTC, merged