feature/BRI-14
brilliant-hamsters/quiz-game pull request #7
Opened 2023-03-26 11:41 UTC by Leliya

feature/BRI-14 (эпик) => feature/BRI-15
Верстка формы авторизации

2023-03-29 15:21 UTC, EfimOstrovskiy approved these changes

2023-04-05 13:27 UTC, AndreyTsvetkov requested changes

2023-04-05 13:27 UTC, AndreyTsvetkov commented on packages/client/src/pages/Login/Login.tsx
> +    if (loggedIn === true) navigate('/')
`if (loggedIn === true)` чем лучше, чем просто `if (loggedIn)`?

2023-04-05 13:27 UTC, AndreyTsvetkov commented on packages/client/src/typings/app.d.ts
кажется, нет причины ему быть .d.ts, а не просто .ts?

2023-04-05 13:27 UTC, AndreyTsvetkov commented on packages/client/src/components/Button/Button.tsx
> +  //isFormValid: boolean
комменты такого рода лучше не оставлять в готовом коде

2023-04-08 11:51 UTC, AndreyTsvetkov approved these changes

2023-04-08 18:51 UTC, merged