feat (BRI-33) Реализация хука валидации
brilliant-hamsters/quiz-game pull request #9
Opened 2023-03-26 16:03 UTC by artemii258

### Какую задачу решаем

Хук для валидации инпутов формы.

2023-03-28 11:12 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  return [validation, objValidation]
Я думаю, здесь нужно поменять местами validation и objValidation. Так как фактически validation является функцией установки состояния objValidation.

2023-03-28 11:21 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +          text: 'латиница, может включать цифры и спецсимволы вроде дефиса, обязательно должна быть «собака» (@) и точка после неё, но перед точкой обязательно должны быть буквы',
Очень длинный текст, в ошибку под инпутом поместить всё не удастся. 
Может сократить до "Невалидный email"?

2023-03-28 11:25 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  const passwordRepeat = (input: HTMLInputElement) => {
Возможно, не стоит делать здесь эту проверку. Каким образом хук будет знать о текущем пароле. Возможно стоит вынести в отдельный хук

2023-03-28 12:00 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  const validation = (e: ChangeEvent<HTMLInputElement>): void => {
Если мы передаем для валидации само событие, то значит проверить значение поля (например, при отправке формы) без ChangeEvent невозможно.
Возможно стоит передавать InputName и value.
Это также способствовало лучшей читабельности кода без постоянного обращения к input.name или input.value (например, стр.61)

2023-03-28 12:14 UTC, Leliya requested changes
Оставила комментарии в коде

2023-03-28 16:01 UTC, artemii258 commented on packages/client/src/utils/hooks/validation.hook.tsx
> +          text: 'латиница, может включать цифры и спецсимволы вроде дефиса, обязательно должна быть «собака» (@) и точка после неё, но перед точкой обязательно должны быть буквы',
можно сделать что бы нижний инпут сдвигался вниз под размер текста, либо да, сократить.

2023-03-28 16:02 UTC, artemii258 commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  return [validation, objValidation]
если это имеет смысл поменяю

2023-03-28 16:12 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +          text: 'латиница, может включать цифры и спецсимволы вроде дефиса, обязательно должна быть «собака» (@) и точка после неё, но перед точкой обязательно должны быть буквы',
Там в форме регистрации места маловато, некуда двигать особо

2023-03-28 16:23 UTC, Leliya commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  const validation = (e: ChangeEvent<HTMLInputElement>): void => {
Посмотрела ещё раз, да ты прав. Этот вопрос снимается

2023-03-29 11:55 UTC, Leliya approved these changes

2023-03-31 15:55 UTC, EfimOstrovskiy approved these changes

2023-04-02 20:17 UTC, Tsvetkraft requested changes
Есть общие соображения. Набор имён, которые вложены в ErrorMessages (Email, Login, etc) частично дублируется в виде набора значений input.name ('email', 'login', 'first_name') и в виде набора имен-ключей для IValidationObj

Нехорошо, что все три набора похожие, но все же разные. 

Я бы предложил подумать про вариант, когда, например, есть тип, описывающий форму, а набор её свойств мы получаем как keyof T. И ключом в IValidationObj является keyof Form, и названия элементам даем такие же, и ошибки храним также в словаре с таким же ключом.

2023-04-02 20:17 UTC, Tsvetkraft commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  Login = 'от 3 до 20 символов, латиница, может содержать цифры, но не состоять из них, без пробелов, без спецсимволов (допустимы дефис и нижнее подчёркивание)',
Если первое укоротили из-за ограничений по размеру, то и второе и третье тоже наверное стоит? 

И в любом случае стоит всем начинаться либо заглавной, либо со строчной буквы, сейчас неконсистентно.

2023-04-02 20:17 UTC, Tsvetkraft commented on packages/client/src/utils/hooks/validation.hook.tsx
> +          text: 'Невалидный email',
тут наверное ErrorMessages должен использоваться

2023-04-05 10:46 UTC, Tsvetkraft approved these changes

2023-04-05 10:46 UTC, Tsvetkraft commented on packages/client/src/utils/hooks/validation.hook.tsx
> +  | 'FirstNameOrSecondName'
все было бы проще, если задублировать сообщения об ошибке для имени и фамилии, тогда и тип можно упростить, и ниже меньше условий. но тут не настаиваю

2023-04-05 13:36 UTC, AndreyTsvetkov approved these changes

2023-04-06 07:38 UTC, merged